## NER & SA

In [1]:
import pandas as pd
import spacy

nlp = spacy.load("en_core_web_sm")

In [2]:
content = "Trinamool Congress leader Mahua Moitra has moved the Supreme Court against her expulsion from the Lok Sabha over the cash-for-query allegations against her. Moitra was ousted from the Parliament last week after the Ethics Committee of the Lok Sabha found her guilty of jeopardising national security by sharing her parliamentary portal's login credentials with businessman Darshan Hiranandani."

In [4]:
doc = nlp(content)

for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_)

Trinamool Congress 0 18 ORG
Mahua Moitra 26 38 PERSON
the Supreme Court 49 66 ORG
Moitra 157 163 NORP
Parliament 184 194 ORG
last week 195 204 DATE
the Ethics Committee 211 231 ORG
Darshan Hiranandani 373 392 PERSON

In [5]:
from spacy import displacy

displacy.render(doc, style='ent')

In [7]:
entities = [(ent.text, ent.label_, ent.lemma_) for ent in doc.ents]
df = pd.DataFrame(entities, columns=['text', 'type', 'lemma'])
print(df)

                   text    type                 lemma
0    Trinamool Congress     ORG    Trinamool Congress
1          Mahua Moitra  PERSON          Mahua Moitra
2     the Supreme Court     ORG     the Supreme Court
3                Moitra    NORP                Moitra
4            Parliament     ORG            Parliament
5             last week    DATE             last week
6  the Ethics Committee     ORG  the Ethics Committee
7   Darshan Hiranandani  PERSON   Darshan Hiranandani

In [19]:
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [9]:
text = "TextBlob is very amazing and simple to use. What a great tool!"

In [11]:
blob = TextBlob(text)

In [18]:
print(blob.words)
print(blob.sentences)
print(blob.tags)
print(blob.noun_phrases)

['TextBlob', 'is', 'very', 'amazing', 'and', 'simple', 'to', 'use', 'What', 'a', 'great', 'tool']
[Sentence("TextBlob is very amazing and simple to use."), Sentence("What a great tool!")]
[('TextBlob', 'NNP'), ('is', 'VBZ'), ('very', 'RB'), ('amazing', 'JJ'), ('and', 'CC'), ('simple', 'JJ'), ('to', 'TO'), ('use', 'VB'), ('What', 'WP'), ('a', 'DT'), ('great', 'JJ'), ('tool', 'NN')]
['textblob', 'great tool']

In [16]:
print(blob.sentiment)

Sentiment(polarity=0.5933333333333334, subjectivity=0.7023809523809524)

Polarity - Range: -1 to +1

Subjectivity - Fact/opinionated - Range: 0 to 1

In [22]:
sid_obj = SentimentIntensityAnalyzer()
sentiment_dict = sid_obj.polarity_scores(text)
sentiment_dict

{'neg': 0.149, 'neu': 0.851, 'pos': 0.0, 'compound': -0.4215}

In [35]:

text = "TextBlob is very amazing and simple to use. What a great tool!"
text = "It happened yesterday night when we were going back to home after office, I guess they were around 5 people. Suddenly they came and started attacking us. I really got frightened.It was such a bad experience for me"

sentiment_dict = sid_obj.polarity_scores(text)
blob = TextBlob(text)

blob.sentiment
sentiment_dict

{'neg': 0.153, 'neu': 0.847, 'pos': 0.0, 'compound': -0.7579}

compound - normalized overall sentiment score (-1 to +1)

## BERT & GPT

In [37]:
df = pd.read_csv("../../data/IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [39]:
df['review_cleaned'] = df['review'].apply(lambda x: x.replace('<br />', ''))

In [42]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification

In [43]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# take one review
review = df['review'].iloc[0]

# tokenize
inputs = tokenizer(review, return_tensors="pt", truncation=True, padding=True)

# model prediction
outputs = model(**inputs)
logits = outputs.logits
pred = torch.argmax(logits, dim=1)

print("Review:", review[:120])
print("Predicted label:", pred.item())

In [44]:
#fine tune

from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset

# load dataset
df = pd.read_csv("../../data/IMDB Dataset.csv")

# take small subset for demo
df = df.sample(500)

# convert labels
df["label"] = df["sentiment"].map({"positive":1, "negative":0})

dataset = Dataset.from_pandas(df[["review","label"]])

# tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize(batch):
    return tokenizer(batch["review"], truncation=True, padding="max_length", max_length=256)

dataset = dataset.map(tokenize, batched=True)
dataset.set_format(type="torch", columns=["input_ids","attention_mask","label"])

# model
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

# training setup
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=1,
    per_device_train_batch_size=8,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset
)

trainer.train()

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/home/asish-jose/AI-ML/venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

KeyboardInterrupt:

### GPT

In [45]:
from transformers import AutoTokenizer, AutoModelForCausalLM

In [ ]:
model_name = "gpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

In [48]:
print(torch.cuda.is_available())

device = torch.device("cpu")
model.to(device)

False

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

In [ ]:
prompt = "Artitificial Intelligence is"

inputs = tokenizer(prompt, return_tensors='pt').to(device)

output = model.generate(
    **inputs,
    max_length=50,
    do_sample=True,  #greedy sampling
    temperature=1.2, #controls randomness by scaling logits before softmax
    top_k=50,        #keeps only top k most probable tokens
    top_p=0.9,        #nucleus sampling
    num_return_sequences=3, #generates multiple outputs
    #num_beams=5,        #beam search (often used for translation/summarization)
)

out = tokenizer.decode(output2[0], skip_special_tokens=True)
print(out)

## lstm

In [51]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset


with open("../../data/quotes/train.txt") as f:
    text = f.read().lower()[:20000]   # take only small portion
text

'i\'m selfish, impatient and a little insecure. i make mistakes, i am out of control and at times hard to handle. but if you can\'t handle me at my worst, then you sure as hell don\'t deserve me at my best.\nyou\'ve gotta dance like there\'s nobody watching,love like you\'ll never be hurt,sing like there\'s nobody listening,and live like it\'s heaven on earth.\nyou know you\'re in love when you can\'t fall asleep because reality is finally better than your dreams.\na friend is someone who knows all about you and still loves you.\ndarkness cannot drive out darkness: only light can do that. hate cannot drive out hate: only love can do that.\nwe accept the love we think we deserve.\nonly once in your life, i truly believe, you find someone who can completely turn your world around. you tell them things that you’ve never shared with another soul and they absorb everything you say and actually want to hear more. you share hopes for the future, dreams that will never come true, goals that were never achieved and the many disappointments life has thrown at you. when something wonderful happens, you can’t wait to tell them about it, knowing they will share in your excitement. they are not embarrassed to cry with you when you are hurting or laugh with you when you make a fool of yourself. never do they hurt your feelings or make you feel like you are not good enough, but rather they build you up and show you the things about yourself that make you special and even beautiful. there is never any pressure, jealousy or competition but only a quiet calmness when they are around. you can be yourself and not worry about what they will think of you because they love you for who you are. the things that seem insignificant to most people such as a note, song or walk become invaluable treasures kept safe in your heart to cherish forever. memories of your childhood come back and are so clear and vivid it’s like being young again. colours seem brighter and more brilliant. laughter seems part of daily life where before it was infrequent or didn’t exist at all. a phone call or two during the day helps to get you through a long day’s work and always brings a smile to your face. in their presence, there’s no need for continuous conversation, but you find you’re quite content in just having them nearby. things that never interested you before become fascinating because you know they are important to this person who is so special to you. you think of this person on every occasion and in everything you do. simple things bring them to mind like a pale blue sky, gentle wind or even a storm cloud on the horizon. you open your heart knowing that there’s a chance it may be broken one day and in opening your heart, you experience a love and joy that you never dreamed possible. you find that being vulnerable is the only way to allow your heart to feel true pleasure that’s so real it scares you. you find strength in knowing you have a true friend and possibly a soul mate who will remain loyal to the end. life seems completely different, exciting and worthwhile. your only hope and security is in knowing that they are a part of your life.\nit is better to be hated for what you are than to be loved for what you are not.\nas he read, i fell in love the way you fall asleep: slowly, and then all at once.\nthe opposite of love is not hate, it\'s indifference. the opposite of art is not ugliness, it\'s indifference. the opposite of faith is not heresy, it\'s indifference. and the opposite of life is not death, it\'s indifference.\nit is not a lack of love, but a lack of friendship that makes unhappy marriages.\ni love you without knowing how, or when, or from where. i love you simply, without problems or pride: i love you in this way because i do not know any other way of loving but this, in which there is no i or you, so intimate that your hand upon my chest is my hand, so intimate that when i fall asleep your eyes close.\nlove all, trust a few, do wrong to none.\nhave you ever been in love? horrible isn\'t it? it makes you so vulnerable. it opens your chest and it opens up your heart and it means that someone can get inside you and mess you up.\nbeing deeply loved by someone gives you strength, while loving someone deeply gives you courage.\nthis life is what you make it. no matter what, you\'re going to mess up sometimes, it\'s a universal truth. but the good part is you get to decide how you\'re going to mess it up. girls will be your friends - they\'ll act like it anyway. but just remember, some come, some go. the ones that stay with you through everything - they\'re your true best friends. don\'t let go of them. also remember, sisters make the best friends in the world. as for lovers, well, they\'ll come and go too. and baby, i hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can\'t give up because if you give up, you\'ll never find your soulmate. you\'ll never find that half who makes you whole and that goes for everything. just because you fail once, doesn\'t mean you\'re gonna fail at everything. keep trying, hold on, and always, always, always believe in yourself, because if you don\'t, then who will, sweetie? so keep your head high, keep your chin up, and most importantly, keep smiling, because life\'s a beautiful thing and there\'s so much to smile about.\nthere is never a time or place for true love. it happens accidentally, in a heartbeat, in a single flashing, throbbing moment.\nlove is that condition in which the happiness of another person is essential to your own.\nyou love me. real or not real?"i tell him, "real.\nyou may not be her first, her last, or her only. she loved before she may love again. but if she loves you now, what else matters? she\'s not perfect—you aren\'t either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. she may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. so don\'t hurt her, don\'t change her, don\'t analyze and don\'t expect more than she can give. smile when she makes you happy, let her know when she makes you mad, and miss her when she\'s not there.\ni am nothing special, of this i am sure. i am a common man with common thoughts and i\'ve led a common life. there are no monuments dedicated to me and my name will soon be forgotten, but i\'ve loved another with all my heart and soul, and to me, this has always been enough..\ni\'m in love with you," he said quietly."augustus," i said."i am," he said. he was staring at me, and i could see the corners of his eyes crinkling. "i\'m in love with you, and i\'m not in the business of denying myself the simple pleasure of saying true things. i\'m in love with you, and i know that love is just a shout into the void, and that oblivion is inevitable, and that we\'re all doomed and that there will come a day when all our labor has been returned to dust, and i know the sun will swallow the only earth we\'ll ever have, and i am in love with you.\nlove looks not with the eyes, but with the mind,and therefore is winged cupid painted blind.\nlove is like the wind, you can\'t see it but you can feel it.\npeople think a soul mate is your perfect fit, and that\'s what everyone wants. but a true soul mate is a mirror, the person who shows you everything that is holding you back, the person who brings you to your own attention so you can change your life. a true soul mate is probably the most important person you\'ll ever meet, because they tear down your walls and smack you awake. but to live with a soul mate forever? nah. too painful. soul mates, they come into your life just to reveal another layer of yourself to you, and then leave. a soul mates purpose is to shake you up, tear apart your ego a little bit, show you your obstacles and addictions, break your heart open so new light can get in, make you so desperate and out of control that you have to transform your life, then introduce you to your spiritual master...\nif you can make a woman laugh, you can make her do anything.\nyou don\'t love someone because they\'re perfect, you love them in spite of the fact that they\'re not.\nwe’re all a little weird. and life is a little weird. and when we find someone whose weirdness is compatible with ours, we join up with them and fall into mutually satisfying weirdness—and call it love—true love.\nlove never dies a natural death. it dies because we don\'t know how to replenish its source. it dies of blindness and errors and betrayals. it dies of illness and wounds; it dies of weariness, of witherings, of tarnishings.\nthere is nothing i would not do for those who are really my friends. i have no notion of loving people by halves, it is not my nature.\nthe real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.\nif i had a flower for every time i thought of you...i could walk through my garden forever.\nto love at all is to be vulnerable. love anything and your heart will be wrung and possibly broken. if you want to make sure of keeping it intact you must give it to no one, not even an animal. wrap it carefully round with hobbies and little luxuries; avoid all entanglements. lock it up safe in the casket or coffin of your selfishness. but in that casket, safe, dark, motionless, airless, it will change. it will not be broken; it will become unbreakable, impenetrable, irredeemable. to love is to be vulnerable.\nwhen someone loves you, the way they talk about you is different. you feel safe and comfortable.\ndumbledore watched her fly away, and as her silvery glow faded he turned back to snape, and his eyes were full of tears."after all this time?""always," said snape.\ni\'ve been making a list of the things they don\'t teach you at school. they don\'t teach you how to love somebody. they don\'t teach you how to be famous. they don\'t teach you how to be rich or how to be poor. they don\'t teach you how to walk away from someone you don\'t love any longer. they don\'t teach you how to know what\'s going on in someone else\'s mind. they don\'t teach you what to say to someone who\'s dying. they don\'t teach you anything worth knowing.\nto die will be an awfully big adventure.\na lady\'s imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.\nso it\'s not gonna be easy. it\'s going to be really hard; we\'re gonna have to work at this everyday, but i want to do that because i want you. i want all of you, forever, everyday. you and me... everyday.\njust when you think it can\'t get any worse, it can. and just when you think it can\'t get any better, it can.\ntis better to have loved and lost, than never to have loved at all.\ni love you as certain dark things are to be loved, in secret, between the shadow and the soul.\nhe’s not perfect. you aren’t either, and the two of you will never be perfect. but if he can make you laugh at least once, causes you to think twice, and if he admits to being human and making mistakes, hold onto him and give him the most you can. he isn’t going to quote poetry, he’s not thinking about you every moment, but he will give you a part of him that he knows you could break. don’t hurt him, don’t change him, and don’t expect for more than he can give. don’t analyze. smile when he makes you happy, yell when he makes you mad, and miss him when he’s not there. love hard when there is love to be had. because perfect guys don’t exist, but there’s always one guy that is perfect for you.\nthe one you love and the one who loves you are never, ever the same person.\nsome people don\'t understand the promises they\'re making when they make them," i said."right, of course. but you keep the promise anyway. that\'s what love is. love is keeping the promise anyway.\ni no longer believed in the idea of soul mates, or love at first sight. but i was beginning to believe that a very few times in your life, if you were lucky, you might meet someone who was exactly right for you. not because he was perfect, or because you were, but because your combined flaws were arranged in a way that allowed two separate beings to hinge together.\nlove is needing someone. love is putting up with someone\'s bad qualities because they somehow complete you.\nwhen i despair, i remember that all through history the way of truth and love have always won. there have been tyrants and murderers, and for a time, they can seem invincible, but in the end, they always fall. think of it--always.\nlove is patient, love is kind. it does not envy, it does not boast, it is not proud. it is not rude, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. love does not delight in evil but rejoices with the truth. it always protects, always trusts, always hopes, always perseveres.\none is loved because one is loved. no reason is needed for loving.\nwhen we love, we always strive to become better than we are. when we strive to become better than we are, everything around us becomes better too.\nwe love the things we love for what they are.\ni would die for you. but i won\'t live for you.\nin vain have i struggled. it will not do. my feelings will not be repressed. you must allow me to tell you how ardently i admire and love you.\nperhaps all the dragons in our lives are princesses who are only waiting to see us act, just once, with beauty and courage. perhaps everything that frightens us is, in its deepest essence, something helpless that wants our love.\nyou are, and always have been, my dream.\nyou are my best friend as well as my lover, and i do not know which side of you i enjoy the most. i treasure each side, just as i have treasured our life together.\ni carry your heart with me (i carry it in my heart)i am never without it (anywherei go you go,my dear; and whatever is done by only me is your doing,my darling)i fear no fate (for you are my fate,my sweet)i want no world (for beautiful you are my world,my true)and it\'s you are whatever a moon has always meant and whatever a sun will always sing is youhere is the deepest secret nobody knows(here is the root of the root and the bud of the bud and the sky of the sky of a tree called life; which growshigher than the soul can hope or mind can hide)and this is the wonder that\'s keeping the stars aparti carry your heart (i carry it in my heart)\nthe only thing worse than a boy who hates you: a boy that loves you.\nso, i love you because the entire universe conspired to help me find you.\nand now i’m looking at you,” he said, “and you’re asking me if i still want you, as if i could stop loving you. as if i would want to give up the thing that makes me stronger than anything else ever has. i never dared give much of myself to anyone before – bits of myself to the lightwoods, to isabelle and alec, but it took years to do it – but, clary, since the first time i saw you, i have belonged to you completely. i still do. if you want me.\nwhere there is love there is life.\nnever love anyone who treats you like you\'re ordinary.\npromise yourselfto be so strong that nothingcan disturb your peace of mind.to talk health, happiness, and prosperityto every person you meet.to make all your friends feelthat there is something in themto look at the sunny side of everythingand make your optimism come true.to think only the best, to work only for the best,and to expect only the best.to be just as enthusiastic about the success of othersas you are about your own.to forget the mistakes of the pastand press on to the greater achievements of the future.to wear a cheerful countenance at all timesand give every living creature you meet a smile.to give so much time to the improvement of yourselfthat you have no time to criticize others.to be too large for worry, too noble for anger, too strong for fear,and too happy to permit the presence of trouble.to think well of yourself and to proclaim this fact to the world,not in loud words but great deeds.to live in faith that the whole world is on your sideso long as you are true to the best that is in you.\ni would always rather be happy than dignified.\nlife will break you. nobody can protect you from that, and living alone won\'t either, for solitude will also break you with its yearning. you have to love. you have to feel. it is the reason you are here on earth. you are here to risk your heart. you are here to be swallowed up. and when it happens that you are broken, or betrayed, or left, or hurt, or death brushes near, let yourself sit by an apple tree and listen to the apples falling all around you in heaps, wasting their sweetness. tell yourself you tasted as many as you could.\nonce upon a time there was a boy who loved a girl, and her laughter was a question he wanted to spend his whole life answering.\nnobody has ever measured, not even poets, how much the heart can hold.\nthe best love is the kind that awakens the soul and makes us reach for more, that plants a fire in our hearts and brings peace to our minds. and that\'s what you\'ve given me. that\'s what i\'d hoped to give you forever\nthere are two basic motivating forces: fear and love. when we are afraid, we pull back from life. when we are in love, we open to all that life has to offer with passion, excitement, and acceptance. we need to learn to love ourselves first, in all our glory and our imperfections. if we cannot love ourselves, we cannot fully open to our ability to love others or our potential to create. evolution and all hopes for a better world rest in the fearlessness and open-hearted vision of people who embrace life.\nwe fell in love, despite our differences, and once we did, something rare and beautiful was created. for me, love like that has only happened once, and that\'s why every minute we spent together has been seared in my memory. i\'ll never forget a single moment of it.\nsome women choose to follow men, and some women choose to follow their dreams. if you\'re wondering which way to go, remember that your career will never wake up and tell you that it doesn\'t love you anymore.\ni think you still love me, but we can’t escape the fact that i’m not enough for you. i knew this was going to happen. so i’m not blaming you for falling in love with another woman. i’m not angry, either. i should be, but i’m not. i just feel pain. a lot of pain. i thought i could imagine how much this would hurt, but i was wrong.\nwe loved with a love that was more than love.\nand so the lion fell in love with the lamb…" he murmured. i looked away, hiding my eyes as i thrilled to the word."what a stupid lamb," i sighed."what a sick, masochistic lion.\nthis is a good sign, having a broken heart. it means we have tried for something.\nevery heart sings a song, incomplete, until another heart whispers back. those who wish to sing always find a song. at the touch of a lover, everyone becomes a poet.\ni heard what you said. i’m not the silly romantic you think. i don’t want the heavens or the shooting stars. i don’t want gemstones or gold. i have those things already. i want…a steady hand. a kind soul. i want to fall asleep, and wake, knowing my heart is safe. i want to love, and be loved.\na guy and a girl can be just friends, but at one point or another, they will fall for each other...maybe temporarily, maybe at the wrong time, maybe too late, or maybe forever\nthe more i know of the world, the more i am convinced that i shall never see a man whom i can really love. i require so much!\neleanor was right. she never looked nice. she looked like art, and art wasn\'t supposed to look nice; it was supposed to make you feel something.\nhe\'s more myself than i am. whatever our souls are made of, his and mine are the same.\ni have decided to stick to love...hate is too great a burden to bear.\nwha

In [ ]:
words = text.lower().split()

# build vocab
vocab = sorted(set(words))
stoi = {w:i for i,w in enumerate(vocab)}
vocab_size = len(vocab)

# encode words
data = torch.tensor([stoi[w] for w in words])

# create input-target sequences
seq_len = 10
X, Y = [], []

for i in range(len(data)-seq_len):
    X.append(data[i:i+seq_len])
    Y.append(data[i+1:i+seq_len+1])

X = torch.stack(X)
Y = torch.stack(Y)

loader = DataLoader(TensorDataset(X,Y), batch_size=32)

In [56]:
class LSTMModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, 64)
        self.lstm = nn.LSTM(64, 128, batch_first=True)
        self.fc = nn.Linear(128, vocab_size)

    def forward(self,x):
        x = self.embed(x)
        out,_ = self.lstm(x)
        return self.fc(out)

model = LSTMModel()
loss_fn = nn.CrossEntropyLoss()
opt = torch.optim.Adam(model.parameters(), lr=0.001)


for Xb,Yb in loader:
    opt.zero_grad()
    out = model(Xb)
    loss = loss_fn(out.view(-1,vocab_size), Yb.view(-1))
    loss.backward()
    opt.step()
    break

## Translation model

In [ ]:
class TranslationModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.src_emb = nn.Embedding(len(src_vocab),32)
        self.tgt_emb = nn.Embedding(len(tgt_vocab),32)

        self.transformer = nn.Transformer(
            d_model=32,
            nhead=2,
            num_encoder_layers=1,
            num_decoder_layers=1
        )

        self.fc = nn.Linear(32,len(tgt_vocab))

    def forward(self,src,tgt):
        src = self.src_emb(src).permute(1,0,2)
        tgt = self.tgt_emb(tgt).permute(1,0,2)

        out = self.transformer(src,tgt)
        return self.fc(out)
    

model = TranslationModel()
loss_fn = nn.CrossEntropyLoss()
opt = torch.optim.Adam(model.parameters())